//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAINPROJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concediu
    {
        public int Id { get; set; }
        public Nullable<int> TipConcediuId { get; set; }
        public Nullable<System.DateTime> Data_inceput { get; set; }
        public Nullable<System.DateTime> Data_sfarsit { get; set; }
        public Nullable<int> InlocuitorId { get; set; }
        public string Comentarii { get; set; }
        public Nullable<int> stareConcediuId { get; set; }
        public Nullable<int> angajatId { get; set; }
    }
}
