//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAINPROJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PrisonBreakEntities : DbContext
    {
        public PrisonBreakEntities()
            : base("name=PrisonBreakEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Concediu> Concedius { get; set; }
    
        public virtual ObjectResult<SelectConcedii_Result> SelectConcedii()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectConcedii_Result>("SelectConcedii");
        }
    }
}
